export enum ApplicationFeatures {
    Account = 'account',
    BusinessAdministration = 'business-administration',
    Conversations = 'conversations',
    Directory = 'directory',
    Documents = 'documents',
    FAQs = 'faqs',
    Invoices = 'invoices',
    Leasing = 'leasing',
    Locations = 'locations',
    Communications = 'communications',
    Notifications = 'notifications',
    Reports = 'reports',
    Requests = 'requests',
    Sales = 'sales',
}
