import { IDPlanFeatures } from './Types/IDPlanFeatures';

export const idPlansFeatureColors: { [featureName: string]: string } = {
    [IDPlanFeatures.Background]: '#939598',
    [IDPlanFeatures.Basic]: '#00a79d',
    [IDPlanFeatures.Dimensions]: '#1b75bc',
    [IDPlanFeatures.Drainage]: '#9398b2',
    [IDPlanFeatures.Dumpster]: '#009444',
    [IDPlanFeatures.Electric]: '#d7df23',
    [IDPlanFeatures.Emergency]: '#ed1c24',
    [IDPlanFeatures.Fire]: '#f15a29',
    [IDPlanFeatures.Gas]: '#8cc6ec',
    [IDPlanFeatures.HVAC]: '#f26522',
    [IDPlanFeatures.Info]: '#27aae1',
    [IDPlanFeatures.Irrigation]: '#39b54a',
    [IDPlanFeatures.Landscape]: '#006838',
    [IDPlanFeatures.Lighting]: '#ffde17',
    [IDPlanFeatures.Location]: '#a97c50',
    [IDPlanFeatures.Parking]: '#939598',
    [IDPlanFeatures.Pavement]: '#414042',
    [IDPlanFeatures.Pylon]: '#a154a1',
    [IDPlanFeatures.Roof]: '#808285',
    [IDPlanFeatures.Satellite]: '#262262',
    [IDPlanFeatures.Signage]: '#fbb040',
    [IDPlanFeatures.Space]: '#f15a29',
    [IDPlanFeatures.Storm]: '#9398b2',
    [IDPlanFeatures.Video]: '#00a79d',
    [IDPlanFeatures.Water]: '#1b75bc',
};
