export enum UserRoles {
    OOAdmin = 18,
    OOReporting = 20,
    OOPropertyManager = 22,
    OOAccounting = 23,
    OORetention = 26,
    OOSalesCoordinator = 27,
    OOTenantServices = 28,
    PRIN = 29,
    OOAssetManagementDirector = 30,
    OORiskManagementCoordinator = 31,
    OOConstructionCoordinator = 32,
    InsuranceCoordinator = 33,
    OOAccountingEscalation = 34,
    OOAssetManagerEscalation = 35,
    OOPropertyManagerEscalation = 36,
    OOCAM = 37,
    OOLegal = 38,
    OOUtility = 39,
    OOLeasingAgent = 40,
    OOConstruction = 41,
}

export const UserRolesDisplayName = {
    [UserRoles.OOAdmin]: "Owner Operator Administrator",
    [UserRoles.OOReporting]: "Owner Operator Reporting",
    [UserRoles.OOPropertyManager]: "Owner Operator Property Manager",
    [UserRoles.OOAccounting]: "Owner Operator Accounting",
    [UserRoles.OORetention]: "Owner Operator Retention",
    [UserRoles.OOSalesCoordinator]: "Owner Operator Sales Coordinator",
    [UserRoles.OOTenantServices]: "Owner Operator Tenant Services",
    [UserRoles.PRIN]: "PRIN",
    [UserRoles.OOAssetManagementDirector]: "Owner Operator Asset Management Director",
    [UserRoles.OORiskManagementCoordinator]: "Owner Operator Risk Management Coordinator",
    [UserRoles.OOConstructionCoordinator]: "Owner Operator Construction Coordinator",
    [UserRoles.InsuranceCoordinator]: "Owner Operator Insurance Coordinator",
    [UserRoles.OOAccountingEscalation]: "Owner Operator Accounting Escalation",
    [UserRoles.OOAssetManagerEscalation]: "Owner Operator Asset Manager Escalation",
    [UserRoles.OOPropertyManagerEscalation]: "Owner Operator Property Manager Escalation",
    [UserRoles.OOCAM]: "Owner Operator Common Area Maintenance",
    [UserRoles.OOLegal]: "Owner Operator Legal",
    [UserRoles.OOUtility]: "Owner Operator Utility",
    [UserRoles.OOLeasingAgent]: "Owner Operator Leasing Agent",
    [UserRoles.OOConstruction]: "Owner Operator Construction",
};
